# Generated by Django 5.1 on 2024-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('user_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('tg_id', models.IntegerField(verbose_name='Telegram ID')),
                ('date_of_registration', models.DateField(verbose_name='Дата регистрации')),
                ('access_granted', models.BooleanField(verbose_name='Доступ разрешен')),
            ],
            options={
                'verbose_name': 'Зарегистрированный пользователь',
                'verbose_name_plural': 'Зарегистрированные пользователи',
            },
        ),
    ]
