# Generated by Django 5.1 on 2024-08-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zacup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='Номер договора')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('booking_time', models.TimeField(verbose_name='Время бронирования')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.botuser')),
            ],
            options={
                'verbose_name': 'Забронированный договор',
                'verbose_name_plural': 'Забронированные договоры',
            },
        ),
    ]
