# Generated by Django 5.1 on 2024-08-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rename_tg_id_zacup_doc_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zacup',
            old_name='organization',
            new_name='bot_user',
        ),
    ]
