# Generated by Django 5.1 on 2024-08-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_rename_organization_zacup_bot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zacup',
            name='booking_time',
        ),
        migrations.AlterField(
            model_name='zacup',
            name='booking_date',
            field=models.DateTimeField(verbose_name='Дата и время бронирования'),
        ),
    ]
