# Generated by Django 5.1 on 2024-08-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_remove_zacup_booking_time_alter_zacup_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zacup',
            name='doc_number',
            field=models.CharField(max_length=250, verbose_name='Номер договора'),
        ),
    ]
