# Generated by Django 5.1 on 2024-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_botuser_tg_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='zacup',
            name='final_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата и время окончания подачи заявок'),
            preserve_default=False,
        ),
    ]
