# Generated by Django 5.1 on 2024-08-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_alter_zacup_final_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zacup',
            name='final_date',
        ),
    ]
