# Generated by Django 5.1 on 2024-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_remove_zacup_final_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='zacup',
            name='final_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания подачи заявок'),
        ),
    ]
