# Generated by Django 5.1 on 2024-08-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_zacup_final_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_tgid', models.IntegerField(verbose_name='Telegram ID администратора')),
                ('check_time', models.CharField(max_length=250, verbose_name='Время проверки статусов')),
                ('bot_token', models.CharField(max_length=250, verbose_name='Токен бота Telegram')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
